---
# file:roles/prepare/tasks/main.yml

- name: install epel
  yum: name=epel-release state=present

- name: install golang binary
  yum: name={{ item }} state=present
  with_items:
    - golang
    - golang-godoc
  when:
    - install_go_env

- name: set GOPATH
  template: src=golang.sh.j2 dest=/etc/profile.d/golang.sh group=root owner=root mode=0755
  when:
    - install_go_env

- name: install compile tools and libs
  yum: name={{ item }} state=present
  with_items:
    - "@development-tools"
    - git
    - mysql-libs
    - mysql-devel
    - python-pip
    - python-devel
    - python-virtualenv
  when:
    - install_compile_env

- name: clone codes
  git: repo=https://github.com/open-falcon/{{ item }}.git dest={{ gopath }}/{{ code_root }}/{{ item }} force=yes
  with_items:
    - agent
    - transfer
    - gateway
    - graph
    - query
    - sender
    - fe
    - hbs
    - judge
    - alarm
    - task
    - dashboard
    - portal
    - links
    - aggregator
    - nodata
  when:
    - clone_code

- name: compile golang modules
  shell: export GOPATH={{ gopath }} && cd {{ gopath }}/{{ code_root }}/{{ item }} && git checkout master --force && git pull && go get ./... && ./control build && ./control pack && mv falcon-{{ item }}*.tar.gz {{ item }}.tar.gz
  when: "'{{ item }}' in compile or 'all' in compile"
  with_items:
    - agent
    - transfer
    - gateway
    - graph
    - query
    - sender
    - fe
    - hbs
    - judge
    - alarm
    - task
    - aggregator
    - nodata

- name: complie python modules
  shell: cd {{ gopath }}/{{ code_root }}/{{ item }}/ && ./control pack && mv falcon-{{ item }}*.tar.gz  {{ item }}.tar.gz
  when:
    - "'{{ item }}' in compile or 'all' in compile"
  with_items:
    - dashboard
    - portal
    - links
